server:
 port: 8089

#sql connections
spring:
 datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://127.0.0.1:3306/project1?useSSL=false&allowMultiQueries=true
  username: root
  password: root
 thymeleaf:
  cache: false
  enabled: true
  prefix: classpath:/static/
  suffix: .html
#mybatis configurations
mybatis:
#mapper config files
 mapper-locations: classpath:mapper/*.xml
 type-aliases-package: com.example.demo.entity
#??????
 configuration:
  map-underscore-to-camel-case: true

